USE TEST;
DELETE * FROM PARTS
WHERE WEIGHT<50;
FROM SUPPLIERS
SET CITY='Burgas'
WHERE SID=GHT65787;
SELECT PART_NAME,COLOR FROM PARTS;
SELECT PART_NAME FROM PARTS WHERE QUANTITY>100;
SELECT NAME FROM SUPPLIERS AND TOTAL FROM SUPPLIERS_PARTS
ORDER BY TOTAL DESC;
