USE TEST;
CREATE TABLE SUPPLIERS_PARTS(
SID CHAR(8) PRIMARY KEY FOREIGN KEY REFERENCES SUPPLIERS(SID) NOT NULL,
PART_ID INT PRIMARY KEY FOREIGN KEY REFERENCES PARTS(PART_ID) NOT NULL,
QUANTITY INT NOT NULL
);
INSERT INTO SUPPLIERS_PARTS
VALUES( '078',81,7);
