USE MEDIADB;
CREATE TABLE CLIENTS(
CLIENT_ID INT PRIMARY KEY NOT NULL,
FNAME VARCHAR(15) NOT NULL,
LNAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(50) NULL
);
INSERT INTO CLIENTS VALUES 
(01,'Peter','Petrov','kv. Komatevo 5 A');
