USE MEDIADB;
CREATE TABLE CLIENTSMEDIA(
CLIENT_ID INT PRIMARY KEY NOT NULL,
MEDIA_ID CHAR(5) PRIMARY KEY NOT NULL,
DATERENT DATETIME NOT NULL,
PRICE DECIMAL(6.2) NULL,
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENTS(CLIENT_ID);
);
INSERT INTO CLIENTSMEDIA VALUES 
(O1,'01','05.05',464546);
